/*day3_assignment*/

/*
 Q3-1
 (1) 원자성
 (2) 완전 함수적 종속
 (3) 이행적 종속 제거
 
 Q3-2
 (1) 제3정규화(3NF)
 (2) 제2정규화(2NF)
 
 Q3-3
 (1) INNER JOIN
 (2) LEFT JOIN
 (3) RIIGHT JOIN
 (4) OUTER JOIN
 
 Q3-4
 (1) 반정규화(DENORMALIZATION)
 
 Q3-5
 (1) INDEX
 (2) INDEX
 (3) INDEX
 (4) INDEX
 
 Q3-6
 (1) TRANSACTION
 (2) ATOMICIY(원자성)
 (3) CONSISTENCY(일관성)
 */

SELECT
	e.DEPTNO ,
	d.DNAME ,
	d.LOC
FROM
	EMP e
LEFT OUTER JOIN DEPT d
			ON
	e.DEPTNO = d.DEPTNO
GROUP BY
	e.DEPTNO,
	d.DNAME ,
	d.LOC
ORDER BY
	e.DEPTNO 
;

-- 실습과제 1
-- 1.
CREATE TABLE DEPT_TEST
AS SELECT *
FROM DEPT
;

INSERT INTO DEPT_TEST (DEPTNO, DNAME, LOC)
VALUES (50, 'ORACLE', 'BUSAN') 
;
INSERT INTO DEPT_TEST (DEPTNO, DNAME, LOC)
VALUES (60, 'SQL', 'ILSAN') 
;
INSERT INTO DEPT_TEST (DEPTNO, DNAME, LOC)
VALUES (70, 'SELECT', 'INCHEON') 
;
INSERT INTO DEPT_TEST (DEPTNO, DNAME, LOC)
VALUES (80, 'DML', 'BUNDANG') 
;

SELECT *
FROM DEPT_TEST
ORDER BY DEPTNO
;

--2.
CREATE TABLE EMP_TEST 
AS SELECT * FROM EMP
;

SELECT * 
FROM EMP_TEST
;

DELETE 
FROM EMP_TEST
; -- 데이터 값만 삭제
ALTER TABLE EMP_TEST 
DROP COLUMN COMM
; -- 컬럼 삭제
ALTER TABLE EMP_TEST 
DROP COLUMN SAL
;  -- 삭제 실수로
ALTER TABLE EMP_TEST 
DROP COLUMN DEPTNO
;
ALTER TABLE EMP_TEST 
ADD SAL NUMBER(7,2)
;  -- 다시 칼럼 추가함
COMMIT
;

INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL)
SELECT 7201, 'TEST_USER1', 'MANAGER', 7788, to_date('02-01-2016','dd-mm-yyyy'), 4500 FROM DUAL UNION ALL
SELECT 7202, 'TEST_USER2', 'CLERK', 7201, to_date('21-02-2016','dd-mm-yyyy'), 1800 FROM DUAL UNION ALL
SELECT 7203, 'TEST_USER3', 'ANALYST', 7201, to_date('11-04-2016','dd-mm-yyyy'), 3400 FROM DUAL UNION ALL
SELECT 7204, 'TEST_USER4', 'SALESMAN', 7201, to_date('31-05-2016','dd-mm-yyyy'), 2700 FROM DUAL UNION ALL
SELECT 7205, 'TEST_USER5', 'CLERK', 7201, to_date('20-07-2016','dd-mm-yyyy'), 2600 FROM DUAL UNION ALL
SELECT 7206, 'TEST_USER6', 'CLERK', 7201, to_date('08-09-2016','dd-mm-yyyy'), 2600 FROM DUAL UNION ALL
SELECT 7207, 'TEST_USER7', 'LECTURER', 7201, to_date('28-10-2016','dd-mm-yyyy'), 2300 FROM DUAL UNION ALL
SELECT 7208, 'TEST_USER8', 'STUDENT', 7201, to_date('09-03-2018','dd-mm-yyyy'), 1200 FROM DUAL
;

SELECT * 
FROM EMP_TEST
;

-- 실습과제 2
--3.
ALTER TABLE EMP_TEST 
ADD DEPTNO NUMBER(2)
;   -- 삭제된 DEPTNO 재생성.. 실습과제1 수행하며 DELETE를 해보라는 취지인줄알고 삭제함

UPDATE EMP_TEST
SET DEPTNO = 80
WHERE EMPNO = 7208
;   -- 과제 상황과 같이 DEPTNO 재지정..

SELECT * 
FROM EMP_TEST
;  -- EMP_TEST 테이블 확인	

UPDATE EMP_TEST
SET DEPTNO = 70
WHERE SAL > (SELECT AVG(SAL)
				FROM EMP_TEST
				WHERE DEPTNO = 50)
;

SELECT
	DEPTNO,
	SAL,
	EMPNO,
	ENAME,
	JOB
FROM
	EMP_TEST
;

--4.
UPDATE EMP_TEST
SET DEPTNO = 60
WHERE EMPNO = 7204
;			--과제 상황과 같이 EMPNO 7204직원 부서를 다시 60으로 정정						

SELECT MIN(HIREDATE)
FROM EMP_TEST
WHERE DEPTNO = 60 
;    		--서브쿼리로 사용할 60번 부서의 입사일이 가장 빠른 날짜 구하기

UPDATE EMP_TEST
SET DEPTNO = 80
	, SAL = SAL*1.2
WHERE HIREDATE > (SELECT MIN(HIREDATE)
					FROM EMP_TEST
					WHERE DEPTNO = 60)
;

SELECT
	DEPTNO,
	SAL,
	EMPNO,
	ENAME,
	JOB
FROM
	EMP_TEST
;

-- 실습과제 3
--1.
CREATE TABLE EMP_USER 
(
EMPNO NUMBER(5, 0),
ENAME VARCHAR2(20),
JOB VARCHAR2(10),
MGR NUMBER(5),
HIREDATE DATE,
SAL NUMBER(7,2),
DEPTNO NUMBER(2,0)
)
;

-- 2.
ALTER TABLE EMP_USER 
ADD RESIGN_DATE DATE
;

-- 3.
ALTER TABLE EMP_USER 
ADD SUR_NAME VARCHAR2(5)
;

-- 4.
ALTER TABLE EMP_USER 
MODIFY SUR_NAME VARCHAR2(10)
;

-- 5.
ALTER TABLE EMP_USER
RENAME COLUMN ENAME TO FULL_NAME
;

--실습과제 4
-- 1.
CREATE TABLE EMP_IDX
AS SELECT *
FROM EMP
;

CREATE INDEX EMP_EMPNO_IDX
ON EMP_IDX(EMPNO)
;

SELECT *
FROM USER_INDEXES
WHERE TABLE_NAME IN('EMP', 'DEPT')
;

-- 2.
SELECT *
FROM USER_INDEXES
WHERE INDEX_NAME = 'EMP_EMPNO_IDX'
;

-- 3.
CREATE VIEW  VW_EMP_IDX
AS (
SELECT
	EMPNO,
	ENAME,
	JOB,
	DEPTNO,
	SAL,
	NVL2(COMM, 'Y', 'N') AS COMM
FROM
	EMP_IDX
WHERE
	SAL >= 2000)
;

SELECT * FROM VW_EMP_IDX
;  -- VIEW 조회

-- 실습과제 5
/*
 1. CONSTRAINT
 2. UNIQUE
 3. NOT NULL
 4. PRIMARY KEY
 5. FOREIGN KEY
 */

